{{- if .Values.global.gardenlet.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: Role
metadata:
  name: gardener.cloud:system:gardenlet-hypershift
  namespace: hypershift
  labels:
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - patch
  - update
{{- end }}
