{{- if .Values.global.gardenlet.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: Role
metadata:
  name: gardener.cloud:system:gardenlet-clusters
  namespace: clusters
  labels:
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - create
  - patch
  - update
{{- end }}
